server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab
    username: postgres
    password: 9502588011
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: truespring.application.name=bank

